baseURL = "https://huynhducduy.me"
languageCode = "en-us"
title = "Duy's Notes"
theme = "cactus-modified"
copyright = "Huynh Duc Duy"
disqusShortname = "huynhducduy"
googleAnalytics = "G-7F7YD46FJ8"
enableEmoji = true

summaryLength = 2

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "About"
url = "/about"
weight = 5

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
	[markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "solarized-dark256"
    tabWidth = 4

[params]
	css = ["css/custom.css"]
  colortheme = "dark" # dark, light, white, or classic
  rss = true
  googleAnalyticsAsync = true

  # Home page settings
  description = "A final year university student, a software engineer who is passionate about web technologies and open source. I'm also a self procliamed internet surfer 🏄‍. Always learning new things, ready for discussions and making new projects."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 10 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = true
    engine = "disqus"

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/huynhducduy"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/huynhducduy"
  [[params.social]]
    name = "email"
    link = "huynhducduy219@gmail.com"
